global:
  smtp_require_tls: true
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: ''
  smtp_auth_username: ''
  smtp_auth_password: ''

route:
  receiver: 'email-alerts'

receivers:
- name: 'email-alerts'
  email_configs:
  - to: ''