# # Overview
# 
# Backs up prometheus.yml config file on prometheus container, updates it, and reloads the service
# Copies the prometheus.yml from <project_root>/resources/prometheus/prometheus.yml to the prometheus container
# Reloads prometheus using the API
#
# Playbook parameters
#
# N/A
#
# Examples
#
# Backup prometheus.yml, copy new one, and reload service
# ansible-playbook update_and_reload_prometheus.yml
#

---
- name: Update and reload prometheus
  hosts: prometheus
  gather_facts: false

  tasks:
    - name: Include update_prometheus tasks
      include_tasks: ./tasks/update_prometheus_config.yml

    - name: Include reload_prometheus tasks
      include_tasks: ./tasks/reload_prometheus.yml