version: '3'
services:

  # alpine_ssh is a modified lightweight alpine:latest to include out-of-the-box ssh and other configurations for ansible
  alpine_ssh:
    build:
      context: ./resources
      dockerfile: alpine-ssh.Dockerfile
    image: alpine-ssh:demo
    profiles: # This tells docker not create a container with this image, only build it
      - donotstart 

  prometheus:
    container_name: prometheus
    build:
      context: ./resources
      dockerfile: prometheus-custom.Dockerfile
    image: prom-custom:demo
    hostname: prometheus
    ports:
      - 9090:9090
    depends_on:
      - ansible

  alertmanager:
    container_name: alertmanager
    build:
      context: ./resources
      dockerfile: alertmanager-custom.Dockerfile
    image: alertm-custom:demo
    hostname: alertmanager
    ports:
      - 9093:9093
    depends_on:
      - prometheus

  grafana:
    container_name: grafana
    build:
      context: ./resources
      dockerfile: grafana-custom.Dockerfile
    image: grafana-custom:demo
    hostname: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - ansible

  ansible:
    container_name: ansible
    build:
      context: ./resources
      dockerfile: ansible-custom.Dockerfile
    image: ansible-custom:demo
    hostname: ansible
    volumes:
      - ./resources:/resources

  webapp:
    container_name: webapp
    build:
      context: ./resources
      dockerfile: webapp.Dockerfile
    image: webapp:demo
    hostname: webapp
    ports:
      - 4000:4000
      - 9115:9115

