version: '3'
services:
  prometheus:
    container_name: prometheus
    build:
      context: ./resources
      dockerfile: prometheus-custom.Dockerfile
    image: prom-custom:demo
    hostname: prom
    ports:
      - 9090:9090
    depends_on:
      - ansible

  grafana:
    container_name: grafana
    build:
      context: ./resources
      dockerfile: grafana-custom.Dockerfile
    image: grafana-custom:demo
    hostname: graf
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - ansible

  ansible:
    container_name: ansible
    build:
      context: ./resources
      dockerfile: ansible-custom.Dockerfile
    image: ansible-custom:demo
    hostname: ans
    volumes:
      - ./resources:/resources
