version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.44.0
    ports:
      - 9090:9090
    depends_on:
      - ansible

  grafana:
    container_name: grafana
    build:
      context: ./dockerfiles
      dockerfile: grafana-custom.Dockerfile
    image: grafana-custom:demo
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - ansible

  ansible:
    container_name: ansible
    build:
      context: ./dockerfiles
      dockerfile: ansible-custom.Dockerfile
    image: ansible-custom:demo
    volumes:
      - ./ansible:/ansible
