# # Overview
#
# Check if ansible's ssh connectivity to hosts is working
# Outputs host IP and hostname if successful
#
# # Playbook parameters
#
# target_hosts | string, list : Hosts to be targetted by playbook
#
# # Examples
#
# Check ssh connecivity to all containers
# ansible-playbook ping.yml -e target_hosts=all
#
---
- name: Ping and retrieve host information
  hosts: "{{ target_hosts }}" 
  gather_facts: true
  
  tasks:
    - name: Ping host
      ping:
      register: ping_result

    - name: Get host IP
      shell: "hostname -i"
      register: ip_result

    - name: Get host hostname
      shell: "hostname -f"
      register: hostname_result

    - name: Output host info
      debug:
        msg: >
          Host details:
          [Hostname: {{ hostname_result.stdout }}]
          [IP: {{ ip_result.stdout }}]
          [Ping: {% if ping_result.failed == false %}Sucessfully pinged host{% else %}Failed to ping host{% endif %}]
      failed_when: ping.result.failed is true
    
