---
- name: Update prometheus.yml
  hosts: prometheus

  tasks:
    - name: Backup prometheus.yml
      copy:
        src: /etc/prometheus/prometheus.yml
        dest: /etc/prometheus/prometheus_BAK.yml
        owner: ansible
        group: orcha 
        mode: 0770
        remote_src: true
     
      
    - name: Move the updated prometheus.yml to target
      copy:
        src: /resources/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        owner: ansible
        group: orcha 
        mode: 0770
        force: true

    - name: Reload prometheus
      uri:
        url: "http://localhost:9090/-/reload"
        method: POST
        return_content: false
      register: reload_output

    - name: Fail if prometheus didn't reload correctly
      fail:
        msg: "Something went wrong while reload Prometheus. Received status code [{{ reload_output.status }}]"
      when: reload_output.status != 200