global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
        labels:
          environment: "demo"
    
  
  - job_name: "node_exporter"
    static_configs:
      - targets: ["ansible:9100"]
        labels:
          container: ansible
          env: demo

      - targets: ["grafana:9100"]
        labels:
          container: grafana
          env: demo

      - targets: ["prometheus:9090"]
        labels:
          container: prometheus
          env: demo