- name: Download node exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"

- name: Create folder to extract to
  file:
    path: "/tmp/node_exporter_extracted"
    state: directory

- name: Extract node exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp/node_exporter_extracted"
    remote_src: true

- name: Copy node exporter binary to correct location
  copy:
    src: /tmp/node_exporter_extracted/node_exporter-1.6.0.linux-amd64/node_exporter
    dest: /usr/bin/node_exporter
    remote_src: true
    owner: ansible
    group: orcha
    mode: 0770
  become: true

- name: Cleanup files and directories
  shell: "rm -Rf /tmp/node_exporter*"
