- name: Check if node exporter is running
  uri:
    url: "http://localhost:9100"
    method: GET
    return_content: false
  register: node_exporter_status
  ignore_errors: true 

- name: Start node exporter
  shell: "nohup /usr/bin/node_exporter > /dev/null 2>&1 &"
  when: node_exporter_status.status != 200

- name: Curl node exporter's endpoint
  uri:
    url: "http://localhost:9100"
    method: GET
    return_content: false
  register: node_exporter_status

- name: Fail if node exporter isn't running
  fail:
    msg: "Node exporter failed to start. Status code returned --> [{{ node_exporter_status.status }}]"
  when: node_exporter_status.status != 200

- name: Output node exporter status
  debug: 
    msg: "Node exporter status on host [{{ ansible_hostname }}] is [{{ node_exporter_status.status }}]"
  when: node_exporter_status.status == 200