---
- name: Ping and retrieve host information
  hosts: all_servers 
  gather_facts: true
  
  tasks:
    - name: Ping host
      ping:
      register: ping_result

    - debug:
        msg: "{{ ping_result }}" 
