---
- name: Stress-test RAM
  hosts: "{{ target_hosts }}"

  vars:
    stress_mem_amount: "{{ stress_mem | default('2G') }}"

  tasks:

    - name: Run RAM stress command
      shell: "/usr/bin/stress \
            --vm 1 \
            --vm-bytes {{ stress_mem_amount }} \
            --timeout {{ duration }} > /dev/null 2>&1 &"

    - name: Wait for stress to finish 
      pause:
        seconds: "{{ duration }}"
        prompt: "\nStressing RAM with [{{ stress_mem_amount }}] for [{{ duration }}] seconds..."
