---

- name: Reload prometheus
  uri:
    url: "http://localhost:9090/-/reload"
    method: POST
    return_content: false
  register: reload_output

- name: Fail if prometheus didn't reload correctly
  fail:
    msg: "Something went wrong while reload Prometheus. Received status code [{{ reload_output.status }}]"
  when: reload_output.status != 200

...